name: Code Checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    env:
      DENO_DIR: deno_cache_dir

    steps:
      - uses: actions/checkout@v4

      - name: Cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.DENO_DIR }}
          key: deno_cache

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.3.x

      # Check if the code is formatted correctly.
      - name: Check formatting (core)
        run: deno fmt --check
        working-directory: ./packages/core
      - name: Check formatting (mongodb)
        run: deno fmt --check
        working-directory: ./packages/mongodb
      - name: Check formatting (oak)
        run: deno fmt --check
        working-directory: ./packages/oak
      - name: Check formatting (utils)
        run: deno fmt --check
        working-directory: ./packages/utils

      # Scan the code for syntax errors and style issues.
      - name: Lint (core)
        run: deno lint
        working-directory: ./packages/core
      - name: Lint (mongodb)
        run: deno lint
        working-directory: ./packages/mongodb
      - name: Lint (oak)
        run: deno lint
        working-directory: ./packages/oak
      - name: Lint (utils)
        run: deno lint
        working-directory: ./packages/utils

      # Run all test files in the repository and collect code coverage.
      - name: Test (core)
        run: deno test --allow-all --permit-no-files
        working-directory: ./packages/core
      - name: Test (mongodb)
        run: deno test --allow-all --permit-no-files
        working-directory: ./packages/mongodb
      - name: Test (oak)
        run: deno test --allow-all --permit-no-files
        working-directory: ./packages/oak
      - name: Test (utils)
        run: deno test --allow-all --permit-no-files
        working-directory: ./packages/utils
